#
# Generated by SM2Gen version:0.9(20Jan2025) Chameleon version:4.5.4 On Python:3.12.3 at 2026-07-02 11:58:01 
#
#
# Routines to be edited by the developer to provide content and validation for parameters
# and provison of the control data for table(s)
#
use esmith::util;
use esmith::util::network;
use esmith::ConfigDB::UTF8;
use esmith::AccountsDB::UTF8;
use esmith::NetworksDB::UTF8;
use esmith::HostsDB;
use esmith::DomainsDB::UTF8;

use constant FALSE => 0;
use constant TRUE  => 1;

use JSON::MaybeXS qw(decode_json encode_json);

#The most common ones - open DB when required.
#my $cdb; 
#my $adb; 
#my $ndb; 
#my $hdb; 
#my $ddb; 

#The most common ones - you might want to use these if you need to make sure that the DB is refreshed.
#$cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
#$adb = esmith::AccountsDB::UTF8->open() || die("Couldn't open Accounts db");
#$ndb = esmith::NetworksDB->open() || die("Couldn't open Network db");
#$hdb = esmith::HostsDB::UTF8->open() 	  || die("Couldn't open Hosts db");
#$ddb = esmith::DomainsDB::UTF8->open()  || die("Couldn't open Domains db");

sub do_extras {
	# Trigger on routeid in URL, like this: hpps:://<domain>/<packagename>x/<routeid>?<other_possible_params>
	# to do background or whatever without switching to another panel
	# see letsencrypt or process_mail for example.
	my $c = shift;
	#branch on the extra route id in the URL
	#if ($c->param('ROUTEID')) {
		#do whatever (e.g. qx or system )
		# set $c->stash('success" or "error" accordingly')
	#} elsif ($c->param('ANOTHERROUTEID')) {
		#do another whatever
	#}
	do_display('<return_or_front_screen_route>');
}

# Validation routines - parameters for each panel

	sub validate_LIST {
		my $c = shift;
		my $smbst_data = shift; #Data hash as parameter
		# Validation for each field 
		my $ret = '';
		
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}


# Get singleton data for each panel

	sub get_data_for_panel_LIST {
		# Return a hash with the fields required which will be loaded into the shared data 
		my $c = shift;
		# If this is a selection from the DB, then be sure to have something like this:
		#my $name = $c->param("Select");
		#my $adb = esmith::AccountsDB::UTF8->open();
		#my $rec = $adb ? $adb->get($name) : undef;
		# and extract data:
		# 	name        => defined $name ? $name : '',
		#	description => $rec ? ($rec->prop('Name') // '') : '',
		#	
		# so that it works if the DB key does not exist or param is ''
		#
		# Read jsno from file for TESTING
		#my $json_file = '/usr/share/smanager/lib/SrvMngr/Controller/smbstatus.json';
		#open my $fh, '<', $json_file
		#	or die "Could not open '$json_file': $!";
		#my $json = do {
		#	local $/;
		#	<$fh>;
		#};
		#close $fh
		#	or die "Could not close '$json_file': $!";

		my $smbstatus = '/usr/bin/smbstatus';
		my %result = ( raw => '', json => '{}' );

		if (!-x $smbstatus) {
		  $result{raw} = "ERROR: smbstatus not found or not executable: $smbstatus";
		  return %result;
		}

		my $json = `$smbstatus -j 2>&1`; my $json_rc = $? >> 8;
		my $raw  = `$smbstatus 2>&1`;    my $raw_rc  = $? >> 8;

		if ($raw_rc != 0 || $raw !~ /\S/) {
		  $result{raw} = $raw =~ /\S/ ? "ERROR: $raw" : 'ERROR: smbstatus returned no output';
		  return %result;
		}

		$result{raw}  = $raw;
		$result{json} = decode_json($json) if $json_rc == 0 && $json =~ /\S/;

		return %result;
	}



# Get control data for table(s)



# Return hash with values from row in which link clicked on table

	sub get_selected_LIST {
		my $c = shift;
		my $selected = shift; #Parameter is name of selected row.
		my $is_new_record = shift; #Indicates new record required (defaults)
		my %ret = ();
		#gather the values here
		return %ret;
	}


#after sucessful modify or create or whatever and submit then perfom (if the params validate)

	sub perform_LIST {
		my $c = shift;
		my $smbst_data = shift; #Data hash as parameter
		my $ret = '';
		my $db = $cdb; #maybe one of the others
		my $dbkey = 'ChangeThis';
		# To make it write to DB as comment, delete this (regex) string in each if statement "TRUE\) \#copy or perform with value: .* e.g."
		
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}


sub create_link{
	# WIP
	my ($c,$route, $panel, $index) = @_;
	my $link = "$route?trt=$panel&Selected=$index";
	return $link;
}

#
# Convert smbstatus -j json to html
#
use HTML::Entities qw(encode_entities);
use Scalar::Util qw(blessed);

sub smbstatus_html {
    my ($c, $data) = @_;

    return qq{<div class="smbstatus smbstatus--error">Not a hash</div>}
        unless ref($data) eq 'HASH';

    my $html = qq{<div class="smbstatus">\n};

    $html .= qq{<div class="smbstatus__meta">\n};
    $html .= qq{<div class="smbstatus__meta-item"><span class="smbstatus__label">Timestamp</span><span class="smbstatus__value">}
          . _scalar_html($data->{timestamp} // '-')
          . qq{</span></div>\n};
    $html .= qq{<div class="smbstatus__meta-item"><span class="smbstatus__label">Version</span><span class="smbstatus__value">}
          . _scalar_html($data->{version} // '-')
          . qq{</span></div>\n};
    $html .= qq{</div>\n};

    for my $section (qw(sessions tcons open_files locks)) {
        next unless ref($data->{$section}) eq 'HASH';

        $html .= qq{<section class="smbstatus__section">\n};
        $html .= qq{<h3 class="smbstatus__title">} . _h($section) . qq{</h3>\n};

        if (!keys %{ $data->{$section} }) {
            $html .= qq{<p class="smbstatus__empty">No entries</p>\n};
            $html .= qq{</section>\n};
            next;
        }

		if ($section eq 'open_files') {
			$html .= _render_open_files_table($data->{$section});
		} else {
			$html .= _render_section_table($section, $data->{$section});
		}
		$html .= qq{</section>\n};
    }

    $html .= qq{</div>\n};
    return $html;
}

sub _render_section_table {
    my ($section, $rows) = @_;

    my $max_len = 1;
    for my $row_key (keys %$rows) {
        my $len = length("$row_key");
        $max_len = $len if $len > $max_len;
    }
    $max_len += 1;
    $max_len = 15 if $max_len > 15;

    my $tree = _collect_column_tree($rows);
    my @leaf_columns;
    _collect_leaf_columns($tree, [], \@leaf_columns);

    my $header_depth = _tree_depth($tree);
    $header_depth = 1 if $header_depth < 1;
    $header_depth = 3 if $header_depth > 3;

    my @header_rows = map { [] } 1 .. $header_depth;

    my %key_label = (
        sessions   => 'Session',
        tcons      => 'TCon',
        open_files => 'Path',
        locks      => 'Lock',
    );

    push @{ $header_rows[0] },
        qq{<th rowspan="$header_depth" scope="col">} . _h($key_label{$section} // 'Key') . qq{</th>};

    _build_header_rows($tree, 1, $header_depth, \@header_rows);

    my $html = qq{<div class="smbstatus__table-wrap">\n};
    $html   .= qq{<table class="smbstatus__table">\n};
    $html   .= qq{<thead>\n};

    for my $row (@header_rows) {
        $html .= qq{<tr>} . join('', @$row) . qq{</tr>\n};
    }

    $html .= qq{</thead>\n<tbody>\n};

    for my $row_key (sort keys %$rows) {
        my $row = $rows->{$row_key};

        $html .= qq{<tr>};
        $html .= qq{<td class="smbstatus__id">} . _scalar_html($row_key, $max_len) . qq{</td>};

        for my $leaf (@leaf_columns) {
            my $value = _fetch_path_value($row, @{ $leaf->{path} });
            $html .= qq{<td>} . _render_cell($value, $max_len) . qq{</td>};
        }

        $html .= qq{</tr>\n};
    }

    $html .= qq{</tbody></table>\n</div>\n};
    return $html;
}

sub _collect_column_tree {
    my ($rows) = @_;
    my %tree;

    for my $row_key (keys %$rows) {
        my $row = $rows->{$row_key};
        next unless ref($row) eq 'HASH';
        _merge_hash_into_tree(\%tree, $row, 1);
    }

    return \%tree;
}

sub _merge_hash_into_tree {
    my ($tree, $href, $depth) = @_;
    return unless ref($href) eq 'HASH';

    for my $k (sort keys %$href) {
        my $v = $href->{$k};

        $tree->{$k} ||= { children => {} };

        if (ref($v) eq 'HASH' && $depth < 3 && keys %$v) {
            _merge_hash_into_tree($tree->{$k}{children}, $v, $depth + 1);
        }
        else {
            $tree->{$k}{leaf} = 1 unless keys %{ $tree->{$k}{children} || {} };
        }
    }
}

sub _collect_leaf_columns {
    my ($tree, $path, $out) = @_;

    for my $k (sort keys %$tree) {
        my $node = $tree->{$k};
        my @path2 = (@$path, $k);

        if ($node->{children} && keys %{ $node->{children} }) {
            _collect_leaf_columns($node->{children}, \@path2, $out);
        }
        else {
            push @$out, { path => \@path2 };
        }
    }
}

sub _tree_depth {
    my ($tree) = @_;
    return 0 unless $tree && ref($tree) eq 'HASH' && keys %$tree;

    my $max = 0;
    for my $k (keys %$tree) {
        my $node = $tree->{$k};
        my $d = 1;

        if ($node->{children} && keys %{ $node->{children} }) {
            $d += _tree_depth($node->{children});
        }

        $max = $d if $d > $max;
    }

    return $max;
}

sub _build_header_rows {
    my ($tree, $level, $max_depth, $rows_out) = @_;

    for my $k (sort keys %$tree) {
        my $node = $tree->{$k};
        my $has_children = $node->{children} && keys %{ $node->{children} };
        my $leaf_count = _count_leaf_nodes($node);

        if ($has_children) {
            push @{ $rows_out->[$level - 1] },
                qq{<th class="smbstatus__group" colspan="$leaf_count" scope="colgroup">}
              . _h($k)
              . qq{</th>};

            _build_header_rows($node->{children}, $level + 1, $max_depth, $rows_out);
        }
        else {
            my $rowspan = $max_depth - $level + 1;
            push @{ $rows_out->[$level - 1] },
                qq{<th rowspan="$rowspan" scope="col">}
              . _h($k)
              . qq{</th>};
        }
    }
}

sub _count_leaf_nodes {
    my ($node) = @_;

    return 1 unless $node->{children} && keys %{ $node->{children} };

    my $count = 0;
    for my $k (keys %{ $node->{children} }) {
        $count += _count_leaf_nodes($node->{children}{$k});
    }

    return $count;
}

sub _fetch_path_value {
    my ($value, @path) = @_;

    for my $part (@path) {
        return undef unless ref($value) eq 'HASH';
        return undef unless exists $value->{$part};
        $value = $value->{$part};
    }

    return $value;
}

sub _render_cell {
    my ($v, $max_len) = @_;

    return qq{<span class="smbstatus__null">-</span>} unless defined $v;

    return _scalar_html($v, $max_len) if !ref($v);

    if (ref($v) eq 'ARRAY') {
        return qq{<ul class="smbstatus__list">}
             . join('', map { qq{<li>} . _render_cell($_, $max_len) . qq{</li>} } @$v)
             . qq{</ul>};
    }

    if (ref($v) eq 'HASH') {
        if (!keys %$v) {
            return qq{<span class="smbstatus__null">-</span>};
        }

        my $s = qq{<table class="smbstatus__kv">\n<tbody>\n};
        for my $k (sort keys %$v) {
            $s .= qq{<tr><th scope="row">} . _h($k) . qq{</th><td>} . _render_cell($v->{$k}, $max_len) . qq{</td></tr>\n};
        }
        $s .= qq{</tbody>\n</table>\n};
        return $s;
    }

    return _scalar_html("$v", $max_len);
}

sub _scalar_html {
    my ($v, $max) = @_;
    $max = 20 unless defined $max;

    $v = '' unless defined $v;
    $v = "$v" if ref($v) || blessed($v);

    my $full = _h($v);
    return $full if length($v) <= $max;

    my $short = substr($v, 0, $max - 1) . "\x{2026}";
    return qq{<span class="smbstatus__trunc" title="$full">} . _h($short) . qq{</span>};
}

sub _h {
    my ($s) = @_;
    $s = '' unless defined $s;
    return encode_entities($s, q{<>&"});
}

sub _render_open_files_table {
    my ($rows) = @_;

    my $max_len = 1;
    for my $row_key (keys %$rows) {
        my $len = length("$row_key");
        $max_len = $len if $len > $max_len;
    }
    $max_len += 1;
    $max_len = 15 if $max_len > 15;

    my $html = qq{<div class="smbstatus__table-wrap">\n};
    $html   .= qq{<table class="smbstatus__table">\n};
    $html   .= qq{<thead><tr>}
            . qq{<th>Path</th>}
            . qq{<th>Filename</th>}
            . qq{<th>Service path</th>}
            . qq{<th>File ID</th>}
            . qq{<th>Pending deletes</th>}
            . qq{<th>Open handles</th>}
            . qq{</tr></thead>\n<tbody>\n};

    for my $path (sort keys %$rows) {
        my $row = $rows->{$path} || {};
        my $fileid = _summarise_fileid($row->{fileid});
        my $opens  = _summarise_opens($row->{opens}, $max_len);

        $html .= qq{<tr>};
        $html .= qq{<td class="smbstatus__id">} . _scalar_html($path, $max_len) . qq{</td>};
        $html .= qq{<td>} . _render_cell($row->{filename}, $max_len) . qq{</td>};
        $html .= qq{<td>} . _render_cell($row->{service_path}, $max_len) . qq{</td>};
        $html .= qq{<td>} . $fileid . qq{</td>};
        $html .= qq{<td>} . _render_cell($row->{num_pending_deletes}, $max_len) . qq{</td>};
        $html .= qq{<td>} . $opens . qq{</td>};
        $html .= qq{</tr>\n};
    }

    $html .= qq{</tbody></table>\n</div>\n};
    return $html;
}

sub _summarise_fileid {
    my ($h) = @_;
    return qq{<span class="smbstatus__null">-</span>}
        unless ref($h) eq 'HASH' && keys %$h;

    my @parts;
    push @parts, 'devid:' . ($h->{devid} // '-') if exists $h->{devid};
    push @parts, 'inode:' . ($h->{inode} // '-') if exists $h->{inode};
    push @parts, 'extid:' . ($h->{extid} // '-') if exists $h->{extid};

    return join ' ', map { _scalar_html($_, 30) } @parts;
}

sub _summarise_opens {
    my ($opens, $max_len) = @_;
    return qq{<span class="smbstatus__null">-</span>}
        unless ref($opens) eq 'HASH' && keys %$opens;

    my @items;

    for my $handle (sort keys %$opens) {
        my $o = $opens->{$handle} || {};

        my @parts;
        push @parts, $handle;

        push @parts, 'uid ' . $o->{uid} if defined $o->{uid};
        push @parts, 'share ' . $o->{share_file_id} if defined $o->{share_file_id};
        push @parts, 'pid ' . $o->{server_id}{pid}
            if ref($o->{server_id}) eq 'HASH' && defined $o->{server_id}{pid};
        push @parts, 'mode ' . $o->{sharemode}{text}
            if ref($o->{sharemode}) eq 'HASH' && length($o->{sharemode}{text} // '');
        push @parts, 'access ' . $o->{access_mask}{text}
            if ref($o->{access_mask}) eq 'HASH' && length($o->{access_mask}{text} // '');
        push @parts, 'opened ' . $o->{opened_at} if defined $o->{opened_at};

        push @items,
            qq{<li>} . join(' · ', map { _scalar_html($_, 40) } @parts) . qq{</li>};
    }

    return qq{<ul class="smbstatus__handles">} . join('', @items) . qq{</ul>};
}

1;
