#
# Generated by SM2Gen version: SM2Gen version:0.9(20Jan2025) Chameleon version:4.5.4 On Python:3.12.3 at 2026-07-02 11:58:01
#
'smbst_LIST_panel_action_was_successful' => 'Smbstatus panel refreshed successfully',
'smbst_SMB_Status' => 'SMB Status',
'smbst_SMBStatus_usage' => 'SMB usage from the Samba project smbstatus programme:',
'smbst_refresh' => 'Refresh',

